[project]
name = "trading-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ccxt>=4.4.85",
    "colorama>=0.4.6",
    "pandas>=2.2.3",
    "pydantic>=2.11.5",
    "typing>=3.10.0.0",
]
